<img src="../../../figs/holberton_logo.png" alt="logo" width="500"/>

# Linear Algebra

Linear algebra plays a fundamental role in many areas of machine learning. It provides the mathematical framework to represent, analyze and solve problems involving large datasets and complex models. Some of the key applications of linear algebra in machine learning include:

- Linear regression: where linear algebra provides the tools to estimate the model coefficients and make predictions.
- Principal component analysis (PCA): where linear algebra is used to find the eigenvectors and eigenvalues of a matrix to perform dimensionality reduction and feature extraction.
- Convolutional neural networks (CNNs): where linear algebra is used to perform operations such as matrix multiplication and convolutions to train and evaluate deep learning models.
- Support vector machines (SVMs): where linear algebra is used to find the optimal separating hyperplane for classification tasks.

Linear algebra provides the necessary tools and concepts to solve many of the fundamental problems in machine learning, and is therefore an essential area of study for anyone interested in the field.

We start our dicussion with an introduction to vectors and matrices. Let's go.

## Vectors

A vector is a mathematical object that represents both magnitude and direction. In linear algebra, a vector is typically represented as a one-dimensional array of numbers. Vectors are conceptualized differently in various fields, such as:

- *Physics*: a quantity having direction as well as magnitude (arrows in space)
- *Computer Science*: ordered lists of numbers
- *Math*: combination of both

In Python, a vector can be created simply as a list

In [1]:
# Create a vector using a list
my_vector = [1, 2, 3, 4, 5]

# Print the vector
print(my_vector)

[1, 2, 3, 4, 5]


### Key operations in vectors

Some of the key mathematical operations that can be performed on vectors include **addition**, **subtraction**, and **scalar multiplication**. Below is defined a function which adds two vectors. Similar functions can be defined for all the other basic mathematical operations

In [2]:
# a function that adds two vectors vec1 and vec2

def add_vectors(vec1, vec2):
    if len(vec1) != len(vec2):
        return None
    
    result = []
    for i in range(len(vec1)):
        result.append(vec1[i] + vec2[i])
    
    return result

v1 = [1, 2, 3]
v2 = [4, 5, 6]
result = add_vectors(v1, v2)
print(result)

[5, 7, 9]


## The Matrix

A matrix is a mathematical object that consists of a rectangular array of numbers. In linear algebra, a matrix is typically represented as a two-dimensional array.
- A matrix is a compact but general way to represent any linear transform
- Examples of linear transforms are rotations, scalings, projections
- An `m` by `n` matrix is a function of two variables, the first of which has domain `{1, 2, ... m}` and the second of which has domain `{1, 2, ... n}`

### Key notation

- The **shape** of a matrix refers to the number of rows and columns in the matrix.
- The **axis** refers to a specific dimension of an array.
- A **slice** means taking elements from one given index to another given index

To find the shape of a matrix, we can use the built-in `len()` function to get the length of the outer list (which gives the number of rows), and then get the length of one of the inner lists (which gives the number of columns)

In [3]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Get the number of rows
num_rows = len(matrix)

# Get the number of columns (assuming all rows have the same length)
num_cols = len(matrix[0])

# Print the shape
print((num_rows, num_cols))  

(3, 3)


To slice a matrix in Python, you can use nested loops to iterate over the rows and columns of the matrix and extract the desired elements. 

In [3]:
the_matrix = [[1, 2, 3], [4, 5, 6], [6, 7, 8]]
the_matrix[0][0]

1

In [4]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Slice the matrix to get the 2x2 sub-matrix in the bottom-right corner
sub_matrix = []
for i in range(1, 3):
    row = []
    for j in range(1, 3):
        row.append(matrix[i][j])
    sub_matrix.append(row)

# Print the sub-matrix
print(sub_matrix)  

[[5, 6], [8, 9]]


To find the axis of a matrix in Python, you can use the same approach as for finding the shape, since the number of rows corresponds to the first axis and the number of columns corresponds to the second axis.

In [5]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Get the number of rows (which corresponds to the first axis)
num_rows = len(matrix)

# Get the number of columns (which corresponds to the second axis)
num_cols = len(matrix[0])

# Print the axis of the matrix
print((num_rows, num_cols))  

(3, 3)


### Key operations

Some of the key operations that can be performed on matrices include *addition, subtraction, scalar multiplication*, and *matrix multiplication*.
Below a function that adds two matrices. Similar functions can be developed for the other basic mathematical operations


In [6]:
# a function that adds two matrices 
def add_matrices(mat1, mat2):
    if len(mat1) != len(mat2) or len(mat1[0]) != len(mat2[0]):
        return None  # matrices have different shapes
    
    result = []
    for i in range(len(mat1)):
        row = []
        for j in range(len(mat1[0])):
            row.append(mat1[i][j] + mat2[i][j])
        result.append(row)
    
    return result

mat1 = [[1,2,3], [4,5,6], [7,8,9]]
mat2 = [[9,8,7], [6,5,4], [3,2,1]]

print(add_matrices(mat1, mat2))

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


#### Matrix multiplication

Matrix multiplication is a binary operation that takes a pair of matrices and produces another matrix. It is used to perform various transformations and calculations in linear algebra, such as rotating, scaling, and shearing objects in space.

The product of two matrices `A` and `B` is denoted by `AB`. Matrix multiplication is defined such that the number of columns in matrix `A` must be equal to the number of rows in matrix `B`. The resulting matrix will have the same number of rows as `A` and the same number of columns as `B`.

In [7]:
def matrix_multiplication(mat1, mat2):
    """
    Perform matrix multiplication of two matrices 
    """
    m1_rows, m1_cols = len(mat1), len(mat1[0])
    m2_rows, m2_cols = len(mat2), len(mat2[0])

    # Check if matrices are valid for multiplication
    if m1_cols != m2_rows:
        return None

    # Initialize the result matrix with zeros
    result = [[0 for _ in range(m2_cols)] for _ in range(m1_rows)]

    # Compute the dot product of each row in the first matrix with each column in the second matrix
    for i in range(m1_rows):
        for j in range(m2_cols):
            dot_product = 0
            for k in range(m1_cols):
                dot_product += mat1[i][k] * mat2[k][j]
            result[i][j] = dot_product

    return result

mat1 = [[1,2,3], [4,5,6], [7,8,9]]
mat2 = [[9,8,7], [6,5,4], [3,2,1]]
print(matrix_multiplication(mat1, mat2))

[[30, 24, 18], [84, 69, 54], [138, 114, 90]]


The function takes two matrices as input and returns their product if they are valid for multiplication, and returns `None` otherwise. It first checks if the number of columns in the first matrix matches the number of rows in the second matrix, which is a requirement for matrix multiplication. Then, it initializes a result matrix with zeros, and computes the dot product of each row in the first matrix with each column in the second matrix. Finally, it populates the result matrix with the computed dot products and returns it.

## NumPy

NumPy is a Python library used for working with large multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. The library can be imported as `import numpy as np`. Below we provide how most of the operations defined above can be written by taking advantage of NumPy's built-in functions

In [8]:
import numpy as np

### Vectors in NumPy

Below we create a vector and then perform the basic mathematical operations with vectors

In [9]:
# create a vector using NumPy
vector = np.array([1, 2, 3])
print(vector)

[1 2 3]


In [10]:
# create two vectors using NumPy
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# add the two vectors
result = v1 + v2
print(result)

# subtract the two vectors
result = v1 - v2
print(result)

# multiply a vector by a scalar
result = 2 * v1
print(result)


[5 7 9]
[-3 -3 -3]
[2 4 6]


### Matrices in NumPy

Below we create a matrix and then perform the basic mathematical operations with matrices

In [11]:
# create a matrix using NumPy
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# create two matrices using NumPy
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

# add the two matrices
result = m1 + m2
print("Add matrices\n", result, "\n")

# subtract the two matrices
result = m1 - m2
print("Subtract matrices\n", result, "\n")

# multiply a matrix by a scalar
result = 2 * m1
print("Multiply matrix by scalar \n", result, "\n")

# multiply two matrices
result = np.dot(m1, m2)
print("Multiply matrices\n", result)


Add matrices
 [[ 6  8]
 [10 12]] 

Subtract matrices
 [[-4 -4]
 [-4 -4]] 

Multiply matrix by scalar 
 [[2 4]
 [6 8]] 

Multiply matrices
 [[19 22]
 [43 50]]


### Shape, axis, slice

In [13]:
# get the shape of the matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
shape = matrix.shape
print(shape)

(3, 3)


In [14]:
v = np.array([1, 2, 3, 4, 5])

# Slice the first three elements of the vector
v_first_three = v[:3]
print(v_first_three)

# Slice the last three elements of the vector
v_last_three = v[-3:]
print(v_last_three)

# Slice middle three elements 
v_middle_three = v[1:4]
print(v_middle_three)


[1 2 3]
[3 4 5]
[2 3 4]


In [15]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice the first row of the matrix
m_sliced = m[0, :]

print(m_sliced)  # [1 2 3]

# Slice the second column of the matrix
m_sliced = m[:, 1]

print(m_sliced)  # [2 5 8]

# Slice a 2x2 submatrix of the matrix
m_sliced = m[1:, :2]

print(m_sliced)  # [[4 5], [7 8]]

[1 2 3]
[2 5 8]
[[4 5]
 [7 8]]


### The end. 