<img src="../../../holberton_logo.png" alt="logo" width="500"/>

# Introduction to NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Machine Learning with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [15]:
my_list = [1,2,3, "Hello", [1, 2, 3, 5]]
my_list[4]

2

In [17]:
import numpy as np
my_list = np.array([1, 2, 3])
my_list.shape

(3,)

In [29]:
my_matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [25]:
my_matrix = np.array(my_matrix)
my_matrix.shape

(3, 3)

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [37]:
np.arange(10, 101, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [43]:
np.zeros((13, 14))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [55]:
np.linspace(0, 101, 10)

array([  0.        ,  11.22222222,  22.44444444,  33.66666667,
        44.88888889,  56.11111111,  67.33333333,  78.55555556,
        89.77777778, 101.        ])

In [65]:
np.linspace(2, 20, 11)

array([ 2. ,  3.8,  5.6,  7.4,  9.2, 11. , 12.8, 14.6, 16.4, 18.2, 20. ])

## eye

Creates an identity matrix

In [69]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [116]:
np.random.rand(3,3)

array([[0.8067335 , 0.84745949, 0.06410977],
       [0.32884761, 0.52281069, 0.20105446],
       [0.47896309, 0.61206944, 0.08243161]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [20]:
np.random.randn(5,5)

array([[-3.83438602e-01,  1.34952943e+00, -1.23085853e-01,
        -1.25451373e+00, -4.28091199e-01],
       [ 7.59685849e-01, -1.76796823e+00, -3.01420782e-01,
         2.32398503e+00,  8.62603268e-02],
       [ 5.11916606e-01, -2.86163715e-02, -4.55292512e-01,
        -2.05092730e+00,  2.18157348e+00],
       [-8.84388031e-01,  6.56533923e-01, -2.75427811e-01,
         8.62272799e-02,  1.37665024e-01],
       [-7.09505436e-04, -3.38721187e-01, -7.09039673e-02,
         3.78691529e-01,  1.14267088e-01]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [120]:
np.random.randint(1,100,10)

array([99, 73, 84, 47, 96, 42, 37, 59, 11, 39])

## Array Attributes and Methods

Let's discuss some useful attributes and methods of an array:

In [17]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[41 27 21 44 26 15 40  5 35 10]


## Reshape
Returns an array containing the same data with a new shape.

In [132]:
arr = np.arange(30)
print(arr)
print(arr.reshape(5, 6))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [134]:
ranarr = np.arange(30)
print(ranarr)
print(ranarr.max())
print(ranarr.min())
print(ranarr.argmax())
print(ranarr.argmin())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
29
0
29
0


## NumPy Indexing and Selection


### Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [150]:
#Creating sample array
arr = np.arange(0,11)
print(arr)

arr[4:6]





[ 0  1  2  3  4  5  6  7  8  9 10]


array([4, 5])

### Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [156]:
#Setting a value with index range (Broadcasting)
arr[3:6]=300

#Show
print(arr)

# Reset array
arr = np.arange(0,11)

#Show
print(arr)



[  0   1   2 300 300 300   6   7   8   9  10]
[ 0  1  2  3  4  5  6  7  8  9 10]


### Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. Use the comma notation for clarity.

In [158]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [182]:
arr_2d[:, 1:3]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [37]:
# Getting individual element value
arr_2d[1][0]

20

In [38]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [39]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [190]:
arr[arr <= 5]

array([0, 1, 2, 3, 4, 5])

In [29]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

## NumPy Operations

### Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [30]:
arr = np.arange(0,10)

In [31]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [33]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
arr / arr

C:\Users\evisp\AppData\Local\Temp\ipykernel_23004\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

### The end.